/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ajustes;

import java.util.HashMap;
import java.util.Locale;
import java.util.ResourceBundle;




/**
 *
 * @author bolli
 */
public class Ajustes extends javax.swing.JFrame {

    private static HashMap<String, String> userData;
    int xMouse;
    int yMouse;
    boolean notificacion;
    
    /**
     * Creates new form Ajustes
     */
    public Ajustes(HashMap<String, String> userData) {
        initComponents();
        jComboBoxIdiomas.addActionListener(evt -> cambiarIdioma());
        jNotificacionONOFF.setVisible(false);
        jNumContacto.setVisible(false);
        jManualUso.setVisible(false);
        jComboBoxIdiomas.setVisible(false);
        //panelManualUso.setVisible(false);
    
    }
    public boolean getNotificacion(){
        return notificacion;
    }
    
    
    //POR IMPLEMENTAR
    private void cambiarIdioma() {
        String selectedLanguage = (String) jComboBoxIdiomas.getSelectedItem();
        if ("English".equals(selectedLanguage)) {
        } else if ("Español".equals(selectedLanguage)) {
        }
    }
    
    private void actualizarTextos(){


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAjustes = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        lblMyPills = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblAjustes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jNotificacionONOFF = new javax.swing.JToggleButton();
        jComboBoxIdiomas = new javax.swing.JComboBox<>();
        jNumContacto = new javax.swing.JToggleButton();
        jManualUso = new javax.swing.JButton();
        lblHelpSupport = new javax.swing.JLabel();
        lblNotification1 = new javax.swing.JLabel();
        lblLanguage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pnlAjustes.setBackground(new java.awt.Color(255, 255, 255));
        pnlAjustes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(204, 204, 204));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        lblMyPills.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMyPills.setText("MyPills");

        lblX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("x");
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblMyPills, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMyPills, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblX))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlAjustes.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 20));

        lblAjustes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAjustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAjustes.setText("Settings");
        pnlAjustes.add(lblAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 46, 169, 50));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jNotificacionONOFF.setText("Notifications OFF");
        jNotificacionONOFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNotificacionONOFFMouseClicked(evt);
            }
        });
        jNotificacionONOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNotificacionONOFFActionPerformed(evt);
            }
        });

        jComboBoxIdiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spanish", "English", "French" }));
        jComboBoxIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomasActionPerformed(evt);
            }
        });

        jNumContacto.setText("Contact number");
        jNumContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumContactoActionPerformed(evt);
            }
        });

        jManualUso.setText("App Manual");
        jManualUso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jManualUsoMouseClicked(evt);
            }
        });
        jManualUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManualUsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNotificacionONOFF, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jComboBoxIdiomas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jManualUso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jNotificacionONOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jComboBoxIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jNumContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jManualUso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pnlAjustes.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 510, 500));

        lblHelpSupport.setBackground(new java.awt.Color(153, 153, 153));
        lblHelpSupport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHelpSupport.setText("HELP AND SUPPORT");
        lblHelpSupport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHelpSupportMouseClicked(evt);
            }
        });
        pnlAjustes.add(lblHelpSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 180, 40));

        lblNotification1.setBackground(new java.awt.Color(153, 153, 153));
        lblNotification1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNotification1.setText("NOTIFICATIONS");
        lblNotification1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotification1MouseClicked(evt);
            }
        });
        pnlAjustes.add(lblNotification1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 140, 40));

        lblLanguage.setBackground(new java.awt.Color(153, 153, 153));
        lblLanguage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLanguage.setText("LANGUAGE");
        lblLanguage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLanguageMouseClicked(evt);
            }
        });
        pnlAjustes.add(lblLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        int x=evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_titleBarMouseDragged

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void jNotificacionONOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotificacionONOFFActionPerformed
        if (jNotificacionONOFF.isSelected()){
            jNotificacionONOFF.setText("Notifications ON");
            notificacion = true;
        }
        else{
            jNotificacionONOFF.setText("Notifictions OFF");
            notificacion=false;
        }
    }//GEN-LAST:event_jNotificacionONOFFActionPerformed

    private void jComboBoxIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomasActionPerformed
        // TODO add your handling code here:  
        
    }//GEN-LAST:event_jComboBoxIdiomasActionPerformed

    private void jNumContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumContactoActionPerformed
        
    }//GEN-LAST:event_jNumContactoActionPerformed

    private void jNotificacionONOFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNotificacionONOFFMouseClicked
       
    }//GEN-LAST:event_jNotificacionONOFFMouseClicked

    private void jManualUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManualUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jManualUsoActionPerformed

    private void jManualUsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jManualUsoMouseClicked
        if (evt.getSource() == jManualUso) {
            jNumContacto.setVisible(false);
            jManualUso.setVisible(false);
            jNotificacionONOFF.setVisible(false);
            jComboBoxIdiomas.setVisible(false);
            //panelManualUso.setVisible(true);
        }
    }//GEN-LAST:event_jManualUsoMouseClicked

    private void lblHelpSupportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHelpSupportMouseClicked
            if(evt.getSource() == lblHelpSupport){
                jNumContacto.setVisible(true);
                jManualUso.setVisible(true);
                jNotificacionONOFF.setVisible(false);
                jComboBoxIdiomas.setVisible(false);
                //panelManualUso.setVisible(false);
            }
    }//GEN-LAST:event_lblHelpSupportMouseClicked

    private void lblNotification1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotification1MouseClicked
        if(evt.getSource() == lblNotification1){
                jNumContacto.setVisible(false);
                jManualUso.setVisible(false);
                jNotificacionONOFF.setVisible(true);
                jComboBoxIdiomas.setVisible(false);
                //panelManualUso.setVisible(false);
            }
    }//GEN-LAST:event_lblNotification1MouseClicked

    private void lblLanguageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLanguageMouseClicked
        if(evt.getSource() == lblLanguage){
                jNumContacto.setVisible(false);
                jManualUso.setVisible(false);
                jNotificacionONOFF.setVisible(false);
                jComboBoxIdiomas.setVisible(true);
                //panelManualUso.setVisible(false);
            }
    }//GEN-LAST:event_lblLanguageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxIdiomas;
    private javax.swing.JButton jManualUso;
    private javax.swing.JToggleButton jNotificacionONOFF;
    private javax.swing.JToggleButton jNumContacto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAjustes;
    private javax.swing.JLabel lblHelpSupport;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblMyPills;
    private javax.swing.JLabel lblNotification1;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel pnlAjustes;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
