/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ajustes;

import java.util.Locale;
import java.util.ResourceBundle;
import mainWindow.mainWindow;




/**
 *
 * @author bolli
 */
public class Ajustes extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    boolean notificacion;
    
    /**
     * Creates new form Ajustes
     */
    public Ajustes() {
        initComponents();
        jNotificacionONOFF.setVisible(false);
        jNumContacto.setVisible(false);
        jManualUso.setVisible(false);
        jComboBoxIdiomas.setVisible(false);
        //panelManualUso.setVisible(false);
        lblConsulta.setVisible(false);
    }
    public boolean getNotificacion(){
        return notificacion;
    }
    
    
   
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAjustes = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        lblMyPills = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblAjustes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jNotificacionONOFF = new javax.swing.JToggleButton();
        jComboBoxIdiomas = new javax.swing.JComboBox<>();
        jNumContacto = new javax.swing.JToggleButton();
        jManualUso = new javax.swing.JButton();
        lblConsulta = new javax.swing.JLabel();
        jButtonSoporte = new javax.swing.JButton();
        jButtonNotificacion = new javax.swing.JButton();
        jButtonIdioma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));

        pnlAjustes.setBackground(new java.awt.Color(255, 255, 255));
        pnlAjustes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(204, 204, 204));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        lblMyPills.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMyPills.setText("MyPills");

        lblX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("x");
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblMyPills, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMyPills, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblX))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlAjustes.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 20));

        lblAjustes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAjustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAjustes.setText("Ajustes");
        pnlAjustes.add(lblAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 46, 169, 50));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jNotificacionONOFF.setText("Notificaciones desactivadas");
        jNotificacionONOFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNotificacionONOFFMouseClicked(evt);
            }
        });
        jNotificacionONOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNotificacionONOFFActionPerformed(evt);
            }
        });

        jComboBoxIdiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spanish", "English", "French" }));
        jComboBoxIdiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomasActionPerformed(evt);
            }
        });

        jNumContacto.setText("Número de contacto");
        jNumContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumContactoActionPerformed(evt);
            }
        });

        jManualUso.setText("Manual de uso de la App");
        jManualUso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jManualUsoMouseClicked(evt);
            }
        });
        jManualUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManualUsoActionPerformed(evt);
            }
        });

        lblConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblConsulta.setForeground(new java.awt.Color(255, 255, 255));
        lblConsulta.setText("Si necesita realizar alguna consulta, llamar al +34 618 89 90 46");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jNotificacionONOFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxIdiomas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jManualUso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNumContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jNotificacionONOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jComboBoxIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jNumContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jManualUso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pnlAjustes.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 510, 500));

        jButtonSoporte.setText("Soporte y ayuda");
        jButtonSoporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSoporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSoporteMouseClicked(evt);
            }
        });
        jButtonSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSoporteActionPerformed(evt);
            }
        });
        pnlAjustes.add(jButtonSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 240, 40));

        jButtonNotificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNotificacion.setLabel("Notificaciones");
        jButtonNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNotificacionMouseClicked(evt);
            }
        });
        jButtonNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotificacionActionPerformed(evt);
            }
        });
        pnlAjustes.add(jButtonNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 40));

        jButtonIdioma.setText("Idioma");
        jButtonIdioma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIdiomaMouseClicked(evt);
            }
        });
        jButtonIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIdiomaActionPerformed(evt);
            }
        });
        pnlAjustes.add(jButtonIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSoporteActionPerformed
       
        
    }//GEN-LAST:event_jButtonSoporteActionPerformed

    private void jButtonNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNotificacionActionPerformed

    private void jButtonIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIdiomaActionPerformed

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        int x=evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_titleBarMouseDragged

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblXMouseClicked

    private void jNotificacionONOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotificacionONOFFActionPerformed
        if (jNotificacionONOFF.isSelected()){
            jNotificacionONOFF.setText("Notificaciones activadas");
            notificacion = true;
        }
        else{
            jNotificacionONOFF.setText("Notificaciones desactivadas");
            notificacion=false;
        }
    }//GEN-LAST:event_jNotificacionONOFFActionPerformed

    private void jComboBoxIdiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomasActionPerformed
        // TODO add your handling code here:  
        
    }//GEN-LAST:event_jComboBoxIdiomasActionPerformed

    private void jNumContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumContactoActionPerformed
        lblConsulta.setVisible(true);
         jNumContacto.setVisible(false);
         jManualUso.setVisible(false);
         jNotificacionONOFF.setVisible(false);
         jComboBoxIdiomas.setVisible(false);
         //panelManualUso.setVisible(false);
    }//GEN-LAST:event_jNumContactoActionPerformed

    private void jButtonNotificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNotificacionMouseClicked
        // TODO add your handling code here:
        if(evt.getSource()==jButtonNotificacion){
            jNotificacionONOFF.setVisible(true);
            jComboBoxIdiomas.setVisible(false);
            jNumContacto.setVisible(false);
            jManualUso.setVisible(false);
            //panelManualUso.setVisible(false);
            lblConsulta.setVisible(false);
        }   
    }//GEN-LAST:event_jButtonNotificacionMouseClicked

    private void jButtonSoporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSoporteMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == jButtonSoporte) {
            jNumContacto.setVisible(true);
            jManualUso.setVisible(true);
            jNotificacionONOFF.setVisible(false);
            jComboBoxIdiomas.setVisible(false);
            //panelManualUso.setVisible(false);
            lblConsulta.setVisible(false);
        }
    }//GEN-LAST:event_jButtonSoporteMouseClicked

    private void jButtonIdiomaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIdiomaMouseClicked
        if (evt.getSource() == jButtonIdioma) {
            jNumContacto.setVisible(false);
            jManualUso.setVisible(false);
            jNotificacionONOFF.setVisible(false);
            jComboBoxIdiomas.setVisible(true);
            //panelManualUso.setVisible(false);
            lblConsulta.setVisible(false);
        }
    }//GEN-LAST:event_jButtonIdiomaMouseClicked

    private void jNotificacionONOFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNotificacionONOFFMouseClicked
       
    }//GEN-LAST:event_jNotificacionONOFFMouseClicked

    private void jManualUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManualUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jManualUsoActionPerformed

    private void jManualUsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jManualUsoMouseClicked
        if (evt.getSource() == jManualUso) {
            jNumContacto.setVisible(false);
            jManualUso.setVisible(false);
            jNotificacionONOFF.setVisible(false);
            jComboBoxIdiomas.setVisible(false);
            //panelManualUso.setVisible(true);
        }
    }//GEN-LAST:event_jManualUsoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ajustes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIdioma;
    private javax.swing.JButton jButtonNotificacion;
    private javax.swing.JButton jButtonSoporte;
    private javax.swing.JComboBox<String> jComboBoxIdiomas;
    private javax.swing.JButton jManualUso;
    private javax.swing.JToggleButton jNotificacionONOFF;
    private javax.swing.JToggleButton jNumContacto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAjustes;
    private javax.swing.JLabel lblConsulta;
    private javax.swing.JLabel lblMyPills;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel pnlAjustes;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
