/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mainWindow;
import javax.swing.*;
import java.awt.*;
import java.util.Locale;
import java.util.ResourceBundle;
import Languages.*;

/**
 *
 * @author salvadorcabreraparra
 */
public class PanelMedicines extends javax.swing.JPanel implements IdiomaListener {

    /**
     * Creates new form PanelMedicines
     */
    public PanelMedicines() {
        initComponents();
        setSize(330, 140);
        IdiomaManager.getInstance().addIdiomaListener(this);
        actualizarTextos();
    }
    
    private void actualizarTextos() {
        //lblName.setText(IdiomaManager.getInstance().getString("medicines_name"));
        //lblDose.setText(IdiomaManager.getInstance().getString("dose_label"));
        // Actualizar el resto de los elementos...
    }
    
    @Override
    public void onIdiomaChanged() {
        actualizarTextos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName1 = new javax.swing.JLabel();
        lblNameMedicine1 = new javax.swing.JLabel();
        lblRemainig1 = new javax.swing.JLabel();
        lblRemainingMedicine1 = new javax.swing.JLabel();
        lblDose1 = new javax.swing.JLabel();
        lblDoseMedicines1 = new javax.swing.JLabel();
        lblFrequency1 = new javax.swing.JLabel();
        lblFrequencyMedicine1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(300, 120));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName1.setFont(new java.awt.Font("PT Mono", 3, 13)); // NOI18N
        lblName1.setText("NAME:");
        add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 20));

        lblNameMedicine1.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        add(lblNameMedicine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 240, 20));

        lblRemainig1.setFont(new java.awt.Font("PT Mono", 3, 13)); // NOI18N
        lblRemainig1.setText("REMAINING:");
        add(lblRemainig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 20));

        lblRemainingMedicine1.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        add(lblRemainingMedicine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 200, 20));

        lblDose1.setFont(new java.awt.Font("PT Mono", 3, 13)); // NOI18N
        lblDose1.setText("DOSE:");
        add(lblDose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 20));

        lblDoseMedicines1.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        add(lblDoseMedicines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 240, 20));

        lblFrequency1.setFont(new java.awt.Font("PT Mono", 3, 13)); // NOI18N
        lblFrequency1.setText("FREQUENCY:");
        add(lblFrequency1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 20));

        lblFrequencyMedicine1.setFont(new java.awt.Font("PT Mono", 0, 13)); // NOI18N
        add(lblFrequencyMedicine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDose1;
    private javax.swing.JLabel lblDoseMedicines1;
    private javax.swing.JLabel lblFrequency1;
    private javax.swing.JLabel lblFrequencyMedicine1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblNameMedicine1;
    private javax.swing.JLabel lblRemainig1;
    private javax.swing.JLabel lblRemainingMedicine1;
    // End of variables declaration//GEN-END:variables
}
