/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.login;

import Cliente.Client;
import Domain.Customer;
import java.awt.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author purru
 */
public class CambiarContrasena extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    
    Customer user;
    Client cliente;
    
    /**
     * Creates new form CambiarContrasena
     * @param cliente
     * @param user
     */
    public CambiarContrasena(Client cliente, Customer user) {
        this.cliente = cliente;
        this.user = user;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        btnX = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        btnMaximizar = new javax.swing.JPanel();
        lblMaximizar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JPanel();
        lblMinimizar = new javax.swing.JLabel();
        windowIcon = new javax.swing.JLabel();
        lblMyPills = new javax.swing.JLabel();
        pnlNewPassword = new javax.swing.JPanel();
        lblTitleNewPassword = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JPasswordField();
        pnlChangePassword = new javax.swing.JPanel();
        labelLogIn = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        txtFieldConfirm = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - this.getWidth()) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - this.getHeight()) / 2);
        setUndecorated(true);

        panelFondo.setBackground(new java.awt.Color(51, 153, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(204, 204, 204));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });
        titleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnX.setBackground(new java.awt.Color(255, 0, 0));
        btnX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnX.setOpaque(false);
        btnX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXMouseExited(evt);
            }
        });
        btnX.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("x");
        lblX.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnX.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 20));

        titleBar.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 20));

        btnMaximizar.setBackground(new java.awt.Color(204, 204, 204));
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.setOpaque(false);
        btnMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaximizarMouseExited(evt);
            }
        });
        btnMaximizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaximizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaximizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaximizar.setToolTipText("");
        lblMaximizar.setMaximumSize(new java.awt.Dimension(8, 17));
        lblMaximizar.setMinimumSize(new java.awt.Dimension(8, 17));
        lblMaximizar.setPreferredSize(new java.awt.Dimension(8, 17));
        btnMaximizar.add(lblMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 20, 20));

        titleBar.add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 20));

        btnMinimizar.setBackground(new java.awt.Color(204, 204, 204));
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setMinimumSize(new java.awt.Dimension(30, 20));
        btnMinimizar.setOpaque(false);
        btnMinimizar.setPreferredSize(new java.awt.Dimension(30, 20));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseExited(evt);
            }
        });
        btnMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimizar.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        btnMinimizar.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 20, 20));

        titleBar.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 30, 20));
        titleBar.add(windowIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        lblMyPills.setFont(new java.awt.Font("PT Mono", 1, 12)); // NOI18N
        lblMyPills.setText("MyPills");
        titleBar.add(lblMyPills, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 20));

        panelFondo.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 20));

        pnlNewPassword.setBackground(new java.awt.Color(255, 255, 255));
        pnlNewPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitleNewPassword.setFont(new java.awt.Font("PT Mono", 3, 36)); // NOI18N
        lblTitleNewPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleNewPassword.setText("New Password");
        pnlNewPassword.add(lblTitleNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 50));

        txtFieldPassword.setForeground(java.awt.Color.lightGray);
        txtFieldPassword.setText("Password");
        txtFieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldPasswordFocusLost(evt);
            }
        });
        pnlNewPassword.add(txtFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 40));

        pnlChangePassword.setBackground(new java.awt.Color(51, 153, 255));
        pnlChangePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlChangePasswordMouseClicked(evt);
            }
        });
        pnlChangePassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogIn.setFont(new java.awt.Font("PT Mono", 1, 18)); // NOI18N
        labelLogIn.setText("Log In");
        pnlChangePassword.add(labelLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1, -1, 50));

        pnlNewPassword.add(pnlChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 230, 50));

        lblError.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        pnlNewPassword.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 230, 60));

        txtFieldConfirm.setForeground(java.awt.Color.lightGray);
        txtFieldConfirm.setText("Password");
        txtFieldConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldConfirmFocusLost(evt);
            }
        });
        pnlNewPassword.add(txtFieldConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 230, 40));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setText("Password:");
        pnlNewPassword.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 30));

        lblConfirm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblConfirm.setText("Confirm Password:");
        pnlNewPassword.add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 230, 30));

        panelFondo.add(pnlNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 500));

        bgImage.setMaximumSize(new java.awt.Dimension(1000, 1000));
        bgImage.setMinimumSize(new java.awt.Dimension(520, 500));
        bgImage.setPreferredSize(new java.awt.Dimension(520, 500));
        panelFondo.add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 520, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnXMouseClicked

    private void btnXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseEntered
        btnX.setOpaque(true);
        lblX.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnXMouseEntered

    private void btnXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXMouseExited
        btnX.setOpaque(false);
        lblX.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnXMouseExited

    private void btnMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseEntered
        btnMaximizar.setOpaque(true);
        lblMaximizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMaximizarMouseEntered

    private void btnMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizarMouseExited
        btnMaximizar.setOpaque(false);
        lblMaximizar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnMaximizarMouseExited

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseEntered
        btnMinimizar.setOpaque(true);
        lblMinimizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMinimizarMouseEntered

    private void btnMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseExited
        btnMinimizar.setOpaque(false);
        lblMinimizar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnMinimizarMouseExited

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_titleBarMouseDragged

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void pnlChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChangePasswordMouseClicked
        if (String.valueOf(txtFieldPassword.getPassword()).equals(String.valueOf(txtFieldConfirm.getPassword())) && 
                !String.valueOf(txtFieldPassword.getPassword()).equals("Password") && 
                String.valueOf(txtFieldPassword.getPassword()) != null){
            
            HashMap<String, Object> session = new HashMap<>();
            session.put("password", String.valueOf(txtFieldPassword.getPassword()));
            session.put("id", user.getId());
            boolean check = (boolean)cliente.sentMessage("/changeUserPassword", session).get("check");
            
            if (check) {
                //JOptionPane confirmacion
            } else {
                //JOptionPane error
            }
            
            new LogIn().setVisible(true);
            dispose();
        } else {
            lblError.setText("<html>Both passwords don't match.<html>");
        }
    }//GEN-LAST:event_pnlChangePasswordMouseClicked

    private void txtFieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldPasswordFocusGained
        if ("Password".equals(String.valueOf(txtFieldPassword.getPassword()))){
            txtFieldPassword.setText("");
            txtFieldPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtFieldPasswordFocusGained

    private void txtFieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldPasswordFocusLost
        if ("".equals(String.valueOf(txtFieldPassword.getPassword()))){
            txtFieldPassword.setText("Password");
            txtFieldPassword.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtFieldPasswordFocusLost

    private void txtFieldConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldConfirmFocusGained
        if ("Password".equals(String.valueOf(txtFieldConfirm.getPassword()))){
            txtFieldConfirm.setText("");
            txtFieldConfirm.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtFieldConfirmFocusGained

    private void txtFieldConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldConfirmFocusLost
        if ("".equals(String.valueOf(txtFieldConfirm.getPassword()))){
            txtFieldConfirm.setText("Password");
            txtFieldConfirm.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtFieldConfirmFocusLost
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JPanel btnMaximizar;
    private javax.swing.JPanel btnMinimizar;
    private javax.swing.JPanel btnX;
    private javax.swing.JLabel labelLogIn;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblMaximizar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblMyPills;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitleNewPassword;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel pnlChangePassword;
    private javax.swing.JPanel pnlNewPassword;
    private javax.swing.JPanel titleBar;
    private javax.swing.JPasswordField txtFieldConfirm;
    private javax.swing.JPasswordField txtFieldPassword;
    private javax.swing.JLabel windowIcon;
    // End of variables declaration//GEN-END:variables
}
